## adj close

2014-02-03부터 2024-02-28에 해당하는 adj close 도출

In [42]:
!pip install yfinance

import yfinance as yf

Requirement already satisfied: yfinance in /Users/justhaji/anaconda3/lib/python3.11/site-packages (0.2.37)
Requirement already satisfied: pandas>=1.3.0 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (2.1.4)
Requirement already satisfied: numpy>=1.16.5 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.31 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (4.9.2)
Requirement already satisfied: appdirs>=1.4.4 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (2022.7)
Requirement already satisfied: frozendict>=2.3.4 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (2.4.0)
Requirement already satisfied: peewee>=3.16.2 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (3.17.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: html5lib>=1.1 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: six>=1.9 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from requests>=2.31->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/justhaji/anaconda3/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2024.2.2)

In [43]:

def fetch_adjusted_close(stock_symbol, start_date, end_date):
    """
    Yahoo Finance에서 주어진 기간 동안 특정 주식의 조정 종가 데이터 import
    
    Args:
    stock_symbol (str): ticker
    start_date (str): start date ('YYYY-MM-DD')
    end_date (str): end date ('YYYY-MM-DD')
    
    Returns:
    pandas.DataFrame: 조정 종가 데이터를 포함하는 DataFrame
    """
    
    # 주식 데이터 import
    stock_data = yf.Ticker(stock_symbol)
    
    # 지정된 기간 동안의 주식 가격 데이터 import
    hist = stock_data.history(start=start_date, end=end_date)
    
    # return adj close
    return hist['Close']

In [44]:
import os
import yfinance as yf

def fetch_adjusted_close_from_folder(folder_path, start_date, end_date):
    """
    Yahoo Finance에서 주어진 기간 동안 특정 주식의 조정 종가 데이터 import
    
    Args:
    stock_symbol (str): ticker
    start_date (str): start date ('YYYY-MM-DD')
    end_date (str): end date ('YYYY-MM-DD')
    
    Returns:
    pandas.DataFrame: 조정 종가 데이터를 포함하는 DataFrame
    """
    # 폴더 내의 모든 파일 목록 import
    ticker_files = [f for f in os.listdir(folder_path) if f.endswith('_d.csv')]
    
    # 각 파일명에서 티커명 추출
    tickers = [filename.split('_')[0] for filename in ticker_files]
        # 각 티커에 대한 adj close data를 딕셔너리에 저장
    adjusted_closes = {}
    for ticker in tickers:
        stock_data = yf.Ticker(ticker)
        hist = stock_data.history(start=start_date, end=end_date)
        adjusted_closes[ticker] = hist['Close']
    
    return adjusted_closes


folder_path = '/Users/justhaji/Desktop/mu-ah/adv 24/FE/Y-FoRM/장플/24 봄 장플/Data_Dividend'
start_date = '2014-02-01'
end_date = '2024-02-29'
ticker_data = fetch_adjusted_close_from_folder(folder_path, start_date, end_date)

In [45]:
import pandas as pd

df = pd.DataFrame(ticker_data)

In [46]:
df

,O,SHW,CINF,SYY,CVX,GD,ALB,NEE,WST,CLX,...,LIN,ITW,MMM,PPG,ADP,EXPD,XOM,GWW,PG,DOV
Date,,,,,,,,,,,,,,,,,,,,,
2014-02-03 00:00:00-05:00,24.167187,53.436569,35.127270,26.330051,72.255913,78.555679,53.852283,17.479681,44.050049,65.179092,...,99.687660,60.655396,68.674118,74.872978,51.924248,35.346649,58.031166,191.275375,56.483566,45.782383
2014-02-04 00:00:00-05:00,24.288870,53.759819,34.861656,26.391088,72.054359,79.520996,53.834961,17.272728,43.660145,64.764000,...,100.401421,61.168873,70.237175,75.029633,52.534046,35.565971,58.011826,192.943756,56.774582,46.146614
2014-02-05 00:00:00-05:00,24.440987,53.049873,34.750977,26.520796,71.202682,78.882759,54.077267,17.123274,43.593575,63.820560,...,100.672150,61.295280,70.591888,75.021156,51.538727,35.443161,57.728271,192.593430,57.043198,45.683041
2014-02-06 00:00:00-05:00,24.489670,54.134434,33.356503,26.917540,72.340408,80.749527,54.414753,17.203739,43.983486,64.197937,...,101.960182,61.713970,71.445473,75.740753,52.008366,35.197506,58.279915,195.952118,57.378967,45.605789
2014-02-07 00:00:00-05:00,24.678282,55.152538,33.740166,27.093025,72.847527,83.118889,54.933975,17.362795,44.744270,64.628143,...,104.240944,62.946373,72.238068,77.273201,52.491989,35.671253,58.786171,195.993973,57.684875,47.151005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-02-22 00:00:00-05:00,52.060314,319.904999,111.352623,79.936935,155.429993,270.996704,117.804199,56.155994,359.708221,151.338333,...,445.712067,257.305969,77.115387,143.380005,253.296829,120.900002,104.760002,958.179993,159.529892,162.573151
2024-02-23 00:00:00-05:00,52.178585,322.029999,112.047890,80.314560,154.660004,272.409760,120.266342,56.264999,367.244202,151.576340,...,446.240479,258.758270,77.408028,144.369995,254.400452,120.150002,103.839996,958.929993,159.996887,163.589981
2024-02-26 00:00:00-05:00,51.735058,322.510010,111.481743,80.334435,154.449997,271.683319,121.133575,55.150002,363.096436,149.761459,...,443.628204,258.380280,76.772575,142.339996,252.093781,119.300003,104.250000,963.630005,159.192078,164.267853
2024-02-27 00:00:00-05:00,51.557644,327.720001,112.554451,80.632561,152.160004,272.360016,128.181091,55.560001,358.099091,150.634186,...,443.488617,260.130981,77.173912,140.910004,249.866638,118.730003,104.029999,969.539978,158.277985,163.580002
2024-02-28 00:00:00-05:00,51.271816,329.679993,112.931877,80.165497,152.339996,272.967010,131.640060,55.040001,357.119598,152.211044,...,449.869781,261.284882,76.471573,140.479996,250.115204,118.769997,104.320000,974.700012,159.023178,164.360001

In [47]:
df.index = pd.to_datetime(df.index)

# 인덱스에서 시간 부분 제거
df.index = df.index.date

df

,O,SHW,CINF,SYY,CVX,GD,ALB,NEE,WST,CLX,...,LIN,ITW,MMM,PPG,ADP,EXPD,XOM,GWW,PG,DOV
2014-02-03,24.167187,53.436569,35.127270,26.330051,72.255913,78.555679,53.852283,17.479681,44.050049,65.179092,...,99.687660,60.655396,68.674118,74.872978,51.924248,35.346649,58.031166,191.275375,56.483566,45.782383
2014-02-04,24.288870,53.759819,34.861656,26.391088,72.054359,79.520996,53.834961,17.272728,43.660145,64.764000,...,100.401421,61.168873,70.237175,75.029633,52.534046,35.565971,58.011826,192.943756,56.774582,46.146614
2014-02-05,24.440987,53.049873,34.750977,26.520796,71.202682,78.882759,54.077267,17.123274,43.593575,63.820560,...,100.672150,61.295280,70.591888,75.021156,51.538727,35.443161,57.728271,192.593430,57.043198,45.683041
2014-02-06,24.489670,54.134434,33.356503,26.917540,72.340408,80.749527,54.414753,17.203739,43.983486,64.197937,...,101.960182,61.713970,71.445473,75.740753,52.008366,35.197506,58.279915,195.952118,57.378967,45.605789
2014-02-07,24.678282,55.152538,33.740166,27.093025,72.847527,83.118889,54.933975,17.362795,44.744270,64.628143,...,104.240944,62.946373,72.238068,77.273201,52.491989,35.671253,58.786171,195.993973,57.684875,47.151005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-02-22,52.060314,319.904999,111.352623,79.936935,155.429993,270.996704,117.804199,56.155994,359.708221,151.338333,...,445.712067,257.305969,77.115387,143.380005,253.296829,120.900002,104.760002,958.179993,159.529892,162.573151
2024-02-23,52.178585,322.029999,112.047890,80.314560,154.660004,272.409760,120.266342,56.264999,367.244202,151.576340,...,446.240479,258.758270,77.408028,144.369995,254.400452,120.150002,103.839996,958.929993,159.996887,163.589981
2024-02-26,51.735058,322.510010,111.481743,80.334435,154.449997,271.683319,121.133575,55.150002,363.096436,149.761459,...,443.628204,258.380280,76.772575,142.339996,252.093781,119.300003,104.250000,963.630005,159.192078,164.267853
2024-02-27,51.557644,327.720001,112.554451,80.632561,152.160004,272.360016,128.181091,55.560001,358.099091,150.634186,...,443.488617,260.130981,77.173912,140.910004,249.866638,118.730003,104.029999,969.539978,158.277985,163.580002
2024-02-28,51.271816,329.679993,112.931877,80.165497,152.339996,272.967010,131.640060,55.040001,357.119598,152.211044,...,449.869781,261.284882,76.471573,140.479996,250.115204,118.769997,104.320000,974.700012,159.023178,164.360001

In [48]:
# 인덱스를 'Date'라는 이름의 열로 변환
df.reset_index(inplace=True)
df.rename(columns={'index': 'Date'}, inplace=True)

df

,Date,O,SHW,CINF,SYY,CVX,GD,ALB,NEE,WST,...,LIN,ITW,MMM,PPG,ADP,EXPD,XOM,GWW,PG,DOV
0,2014-02-03,24.167187,53.436569,35.127270,26.330051,72.255913,78.555679,53.852283,17.479681,44.050049,...,99.687660,60.655396,68.674118,74.872978,51.924248,35.346649,58.031166,191.275375,56.483566,45.782383
1,2014-02-04,24.288870,53.759819,34.861656,26.391088,72.054359,79.520996,53.834961,17.272728,43.660145,...,100.401421,61.168873,70.237175,75.029633,52.534046,35.565971,58.011826,192.943756,56.774582,46.146614
2,2014-02-05,24.440987,53.049873,34.750977,26.520796,71.202682,78.882759,54.077267,17.123274,43.593575,...,100.672150,61.295280,70.591888,75.021156,51.538727,35.443161,57.728271,192.593430,57.043198,45.683041
3,2014-02-06,24.489670,54.134434,33.356503,26.917540,72.340408,80.749527,54.414753,17.203739,43.983486,...,101.960182,61.713970,71.445473,75.740753,52.008366,35.197506,58.279915,195.952118,57.378967,45.605789
4,2014-02-07,24.678282,55.152538,33.740166,27.093025,72.847527,83.118889,54.933975,17.362795,44.744270,...,104.240944,62.946373,72.238068,77.273201,52.491989,35.671253,58.786171,195.993973,57.684875,47.151005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2530,2024-02-22,52.060314,319.904999,111.352623,79.936935,155.429993,270.996704,117.804199,56.155994,359.708221,...,445.712067,257.305969,77.115387,143.380005,253.296829,120.900002,104.760002,958.179993,159.529892,162.573151
2531,2024-02-23,52.178585,322.029999,112.047890,80.314560,154.660004,272.409760,120.266342,56.264999,367.244202,...,446.240479,258.758270,77.408028,144.369995,254.400452,120.150002,103.839996,958.929993,159.996887,163.589981
2532,2024-02-26,51.735058,322.510010,111.481743,80.334435,154.449997,271.683319,121.133575,55.150002,363.096436,...,443.628204,258.380280,76.772575,142.339996,252.093781,119.300003,104.250000,963.630005,159.192078,164.267853
2533,2024-02-27,51.557644,327.720001,112.554451,80.632561,152.160004,272.360016,128.181091,55.560001,358.099091,...,443.488617,260.130981,77.173912,140.910004,249.866638,118.730003,104.029999,969.539978,158.277985,163.580002
2534,2024-02-28,51.271816,329.679993,112.931877,80.165497,152.339996,272.967010,131.640060,55.040001,357.119598,...,449.869781,261.284882,76.471573,140.479996,250.115204,118.769997,104.320000,974.700012,159.023178,164.360001

In [49]:
df.columns

Index(['Date', 'O', 'SHW', 'CINF', 'SYY', 'CVX', 'GD', 'ALB', 'NEE', 'WST',
       'CLX', 'ED', 'CHD', 'MDT', 'CAH', 'NUE', 'ABBV', 'BEN', 'CAT', 'CB',
       'APD', 'TROW', 'AMCR', 'LEG', 'SPGI', 'MKC', 'CTAS', 'AOS', 'SJM',
       'BF-B', 'PNR', 'BDX', 'TGT', 'MCD', 'WMT', 'FRT', 'GPC', 'ABT', 'CHRW',
       'ROP', 'LOW', 'KO', 'NDSN', 'JNJ', 'ECL', 'AFL', 'PEP', 'CL', 'SWK',
       'BRO', 'ATO', 'IBM', 'HRL', 'ADM', 'ESS', 'EMR', 'KMB', 'LIN', 'ITW',
       'MMM', 'PPG', 'ADP', 'EXPD', 'XOM', 'GWW', 'PG', 'DOV'],
      dtype='object')

In [51]:
sorted_columns = sorted([col for col in df.columns if col != 'Date'])
df = df[['Date'] + sorted_columns]

df

,Date,ABBV,ABT,ADM,ADP,AFL,ALB,AMCR,AOS,APD,...,SHW,SJM,SPGI,SWK,SYY,TGT,TROW,WMT,WST,XOM
0,2014-02-03,31.093279,29.434923,29.425974,51.924248,23.695534,53.852283,6.095217,19.414000,75.011894,...,53.436569,70.876244,66.676048,60.082420,26.330051,41.390232,53.346066,19.509260,44.050049,58.031166
1,2014-02-04,31.487291,29.763350,28.911718,52.534046,23.988226,53.834961,6.095217,19.546049,75.178177,...,53.759819,70.710243,69.033318,60.455746,26.391088,41.173622,54.763107,19.528055,43.660145,58.011826
2,2014-02-05,31.342821,29.845461,29.236910,51.538727,24.101395,54.077267,6.055978,19.721252,75.380608,...,53.049873,70.038689,68.925751,60.090355,26.520796,41.136257,54.142719,19.565645,43.593575,57.728271
3,2014-02-06,31.474159,30.091768,29.577213,52.008366,24.089684,54.414753,6.055978,19.601591,77.535179,...,54.134434,70.619690,69.329079,60.733753,26.917540,41.726387,54.579796,19.552223,43.983486,58.279915
4,2014-02-07,32.104557,30.526941,30.167103,52.491989,24.460419,54.933975,6.167158,19.981915,78.973969,...,55.152538,70.453697,71.677422,62.592476,27.093025,42.077461,55.933365,19.801922,44.744270,58.786171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2530,2024-02-22,175.114609,118.432640,53.700001,253.296829,79.650002,117.804199,9.133359,80.300003,229.814468,...,319.904999,124.290001,434.316345,87.872765,79.936935,150.339996,109.730644,58.271538,359.708221,104.760002
2531,2024-02-23,176.442200,118.870468,53.450001,254.400452,80.410004,120.266342,9.143223,81.086960,231.095062,...,322.029999,125.919998,437.359985,88.338539,80.314560,151.479996,109.819695,58.321369,367.244202,103.839996
2532,2024-02-26,177.155533,118.104271,53.169998,252.093781,79.699997,121.133575,9.015000,81.276230,227.690048,...,322.510010,125.250000,433.410004,86.207870,80.334435,150.149994,109.295280,59.397701,363.096436,104.250000
2533,2024-02-27,177.333878,118.810768,52.790001,249.866638,80.209999,128.181091,8.950000,81.983505,230.042786,...,327.720001,122.639999,427.839996,87.704300,80.632561,151.990005,109.691063,59.387737,358.099091,104.029999
2534,2024-02-28,176.353043,119.457558,53.009998,250.115204,80.559998,131.640060,8.870000,82.571228,230.717834,...,329.679993,121.830002,429.390015,87.179062,80.165497,151.440002,111.165352,59.417633,357.119598,104.320000

In [52]:
# 결과 데이터프레임 저장
output_path = 'adj close.csv'
df.to_csv(output_path, index=False)